
# This file is automatically generated, you probably don't want to edit this

mergevariablesOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mergevariablesOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            variables = NULL,
            targetName = "mergedVar",
            runTrigger = FALSE, ...) {

            super$initialize(
                package="MultipleEncoding",
                name="mergevariables",
                requiresData=TRUE,
                ...)

            private$..variables <- jmvcore::OptionVariables$new(
                "variables",
                variables)
            private$..targetName <- jmvcore::OptionString$new(
                "targetName",
                targetName,
                default="mergedVar")
            private$..runTrigger <- jmvcore::OptionAction$new(
                "runTrigger",
                runTrigger)
            private$..newColumn <- jmvcore::OptionOutput$new(
                "newColumn")

            self$.addOption(private$..variables)
            self$.addOption(private$..targetName)
            self$.addOption(private$..runTrigger)
            self$.addOption(private$..newColumn)
        }),
    active = list(
        variables = function() private$..variables$value,
        targetName = function() private$..targetName$value,
        runTrigger = function() private$..runTrigger$value,
        newColumn = function() private$..newColumn$value),
    private = list(
        ..variables = NA,
        ..targetName = NA,
        ..runTrigger = NA,
        ..newColumn = NA)
)

mergevariablesResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mergevariablesResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        newColumn = function() private$.items[["newColumn"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Merge Variables")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Output"))
            self$add(jmvcore::Output$new(
                options=options,
                name="newColumn",
                title="Merged Variable",
                initInRun=TRUE))}))

mergevariablesBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mergevariablesBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "MultipleEncoding",
                name = "mergevariables",
                version = c(1,0,0),
                options = options,
                results = mergevariablesResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Merge Variables
#'
#' 
#' @param data .
#' @param variables Select the variables whose text values will be merged
#' @param targetName Name of the new merged variable
#' @param runTrigger Click Run to execute the merge
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$newColumn} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' @export
mergevariables <- function(
    data,
    variables,
    targetName = "mergedVar",
    runTrigger = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mergevariables requires jmvcore to be installed (restart may be required)")

    if ( ! missing(variables)) variables <- jmvcore::resolveQuo(jmvcore::enquo(variables))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(variables), variables, NULL))


    options <- mergevariablesOptions$new(
        variables = variables,
        targetName = targetName,
        runTrigger = runTrigger)

    analysis <- mergevariablesClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

