
# This file is automatically generated, you probably don't want to edit this

multipleencodingOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "multipleencodingOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            columnToSplit = NULL,
            separator = ",",
            runTrigger = FALSE, ...) {

            super$initialize(
                package="MultipleEncoding",
                name="multipleencoding",
                requiresData=TRUE,
                ...)

            private$..columnToSplit <- jmvcore::OptionVariable$new(
                "columnToSplit",
                columnToSplit)
            private$..separator <- jmvcore::OptionString$new(
                "separator",
                separator,
                default=",")
            private$..runTrigger <- jmvcore::OptionAction$new(
                "runTrigger",
                runTrigger)
            private$..newColumns <- jmvcore::OptionOutput$new(
                "newColumns")

            self$.addOption(private$..columnToSplit)
            self$.addOption(private$..separator)
            self$.addOption(private$..runTrigger)
            self$.addOption(private$..newColumns)
        }),
    active = list(
        columnToSplit = function() private$..columnToSplit$value,
        separator = function() private$..separator$value,
        runTrigger = function() private$..runTrigger$value,
        newColumns = function() private$..newColumns$value),
    private = list(
        ..columnToSplit = NA,
        ..separator = NA,
        ..runTrigger = NA,
        ..newColumns = NA)
)

multipleencodingResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "multipleencodingResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        newColumns = function() private$.items[["newColumns"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Multiple Encoding")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Output of Encoding"))
            self$add(jmvcore::Output$new(
                options=options,
                name="newColumns",
                title="New Columns",
                initInRun=TRUE))}))

multipleencodingBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "multipleencodingBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "MultipleEncoding",
                name = "multipleencoding",
                version = c(1,0,0),
                options = options,
                results = multipleencodingResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Multiple Encoding
#'
#' 
#' @param data .
#' @param columnToSplit .
#' @param separator The character used to separate values
#' @param runTrigger Click Run to execute the encoding
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$newColumns} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' @export
multipleencoding <- function(
    data,
    columnToSplit,
    separator = ",",
    runTrigger = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("multipleencoding requires jmvcore to be installed (restart may be required)")

    if ( ! missing(columnToSplit)) columnToSplit <- jmvcore::resolveQuo(jmvcore::enquo(columnToSplit))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(columnToSplit), columnToSplit, NULL))


    options <- multipleencodingOptions$new(
        columnToSplit = columnToSplit,
        separator = separator,
        runTrigger = runTrigger)

    analysis <- multipleencodingClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

